### ISSUE TITLE
Include chemical regulation only for information poor genes

### ISSUE THREAD

**Issue by rankishore** [WormBase/genedesc_generator#22] opened 2018-10-10 22:33 UTC
For information-poor C. elegans and brugia malayi genes only-
Template:
\<gene name\> is affected by \<count of chemicals\> chemicals based on \<method1\>, \<method2\> and \<method3/> study (studies).

Placement is always after expression pattern and Anatomy and Gene regulation sentences (when present).

Files to be used:
molReg files at ftp://caltech.wormbase.org/pub/wormbase/ExprClusterSummary/WS269/

**Comment by rankishore** [comment] 2018-10-29 17:47
I don't see any chemical regulation expression cluster data in the WS269 pre-release file, 10-29-2018.

**Comment by valearna** [comment] 2018-10-29 20:32
Duplicate of #27. Closing

**Comment by valearna** [comment] 2018-10-29 22:16
Template Change:

For information-poor C. elegans and brugia malayi genes only-
Template:
1. when less than 4 chemicals:
<gene name> is affected by \<chemical 1\>, \<chemical 2\>, and \<chemical 3\> based on <method1>, <method2> and <method3/> studies
2. when more than 3 chemicals:
<gene name> is affected by <count of chemicals> chemicals including \<chemical 1\>, \<chemical 2\>, and \<chemical 3\> based on <method1>, <method2> and <method3/> studies.
pick the first 3 chemicals in the file. In the future we might need a better way to sort them

**Closed** 2018-11-07 20:06 UTC
Labels: Exp_cluster_module_chem_reg, enhancement, informaton_poor_module
